# Generated by Django 2.2.6 on 2021-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_auto_20210715_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='confirmation_code'),
        ),
    ]
