# Generated by Django 2.2.6 on 2021-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0016_auto_20210722_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='0711', max_length=128, verbose_name='confirmation_code'),
        ),
    ]
