# Generated by Django 2.2.6 on 2021-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_titles', '0002_auto_20210721_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
